# Generated by Django 4.2.23 on 2025-07-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name',
            field=models.CharField(default='test@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='cvbuilder.cv'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='cvbuilder.cv'),
        ),
    ]
