# Generated by Django 4.2.23 on 2025-07-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0002_qualification_workhistory_cv_address_cv_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='cv',
            name='surname',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
