# Generated by Django 4.2.23 on 2025-07-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_rename_full_name_cv_first_name_cv_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Sir', 'Sir'), ('Mx', 'Mx')], max_length=10),
        ),
    ]
